### ISSUE TITLE
pypi over SSL

### ISSUE THREAD

**Issue by gvenka008c** [codekoala/docker-pypi#2]
@codekoala We installed the pypi docker version on our mesos environment. We enabled SSL for accessing pypi.

When we hit https://pypicloud.staging.net/ it is giving a blank page. But a curl returns 200 OK status.

https://pypicloud.staging.net/simple/ gives the list.

Any thoughts on how to have pypi working with SSL? Please suggest.

**Comment by codekoala** [comment]
Whoa, I apologize for the crazy late response! Lots of messages fall through the cracks far too often.

If you still need help with this, a simple option comes to mind: terminate SSL with a reverse proxy such as nginx and proxy http requests through to pypi-server. You could either run the reverse proxy separately or build your own Docker image based on this one and simply run both the proxy and pypi-server within the same image.

Hope that helps. Sorry again for the delay.
