### ISSUE TITLE
why packages does not cache in /srv/pypi

### ISSUE THREAD

**Issue by mrgaolei** [codekoala/docker-pypi#4]
```
--trusted-host=localhost
--index-url http://localhost:8080/
Django==1.10.7
```
```bash
pip install -r requirements.txt
```
There is no any whl in /srv/pypi

**Comment by codekoala** [comment]
Hello @mrgaolei, thank you for the report. I will look into it.

**Comment by reverland** [comment]
any update on this?

**Comment by codekoala** [comment]
Apologies for taking so long to get back to this. The pypi server implementation supplied by this Docker image does not handle caching automatically. For that, you may want to look into something like [devpi](https://pypi.python.org/pypi/devpi-server).

You can easily upload packages by using [pypi-uploader](https://pypi.python.org/pypi/pypi-uploader):

```bash
$ pypiupload packages -i http://localhost:8080 django==1.10.7
```

Note that this does not *install* the specified packages within your environment, it simply downloads the upstream package and immediately uploads it into pypi-server. In other words, this requires a two-stage approach: first upload packages then install from the custom pypi server.
