### ISSUE TITLE
pypiserver's dev version now falls back to the correct URL

### ISSUE THREAD

**Issue by alexntt** [codekoala/docker-pypi#8]
So https://github.com/codekoala/docker-pypi/commit/33271194005c073fabd9778d704bfbb55972dc67 shouldn't be necessary, but for the moment, that would require installing with `pip --pre`. I'm not sure it's worth reverting the change and uploading a new version to Docker Hub until they don't make an official release- we personally would be happy with either option (have a pre release on Docker Hub or wait until the definitive version).

**Comment by codekoala** [comment]
Oh, my apologies for forgetting to circle back to https://github.com/codekoala/docker-pypi/pull/6. This is precisely why I merged and PR. I'd rather wait for a proper upstream release before pushing a new image to Docker Hub with 3327119 reverted. Thank you for your patience.

**Comment by alexntt** [comment]
That's cool, I'm testing the pre release and I've hit a bug ( https://github.com/pypiserver/pypiserver/issues/175 ), so it's fine. I'll try to ping here when there is a proper release which works for us.

**Comment by alexntt** [comment]
Hi, 1.2.1 was released yesterday which seems to work correctly and has that bug fixed- if you could make a new release reverting the change it would be fantastic.

**Comment by ZaiusDR** [comment]
Hi, I'm interested in this fix as well. It would be really nice if you could update the Dockerfile.

**Comment by codekoala** [comment]
@alexntt  @ZaiusDR apologies for the delays. I pushed out an update, and the docker images are done building. I'll wait for confirmation from one or both of you before I close this ticket.

Thank you for your contributions!

**Comment by ZaiusDR** [comment]
Hi @codekoala, it seems to work fine. Thank you!

**Comment by codekoala** [comment]
Thank you for confirming!
